apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  windows: false
  cloudProvider: ""
  
  # Use NetApp official images for Kubernetes 1.29 deployment
  tridentImage: "netapp/trident:25.02.0"
  autosupportImage: "netapp/trident-autosupport:25.02"
  
  # Specify CSI sidecar images explicitly for offline deployment
  nodeDriverRegistrarImage: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.13.0"
  csiAttacherImage: "registry.k8s.io/sig-storage/csi-attacher:v4.7.0"
  csiProvisionerImage: "registry.k8s.io/sig-storage/csi-provisioner:v5.1.0"
  csiResizerImage: "registry.k8s.io/sig-storage/csi-resizer:v1.12.0"
  csiSnapshotterImage: "registry.k8s.io/sig-storage/csi-snapshotter:v8.2.0"
  
  # Optimized settings for K8s 1.29
  disableAuditLog: true
  silenceAutosupport: false
  enableForceDetach: false 